# Test config for SAIGE-null C++ standalone
# Sparse GRM with x1 only covariate
paths:
  plinkFile: /Users/francis/Desktop/Zhou_lab/SAIGE_gene_pixi/Jan_30_comparison/code_copy/SAIGE_isolated/extdata/input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly_22chr
  out_prefix: /Users/francis/Desktop/Zhou_lab/SAIGE_gene_pixi/Jan_30_comparison/output/cpp_sparse_x1_output
  out_prefix_vr: /Users/francis/Desktop/Zhou_lab/SAIGE_gene_pixi/Jan_30_comparison/output/cpp_sparse_x1_vr
  sparse_grm: /Users/francis/Desktop/Zhou_lab/SAIGE_gene_pixi/SAIGE/extdata/output/sparseGRM_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx
  sparse_grm_ids: /Users/francis/Desktop/Zhou_lab/SAIGE_gene_pixi/SAIGE/extdata/output/sparseGRM_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx.sampleIDs.txt
  overwrite_varratio: true

design:
  csv: /Users/francis/Desktop/Zhou_lab/SAIGE_gene_pixi/Jan_30_comparison/code_copy/cpp_standalone/design_dense_x1.csv
  covar_cols:
    - x1

fit:
  trait: quantitative
  loco: false
  nthreads: 1
  maxiter: 20
  tol: 0.02
  tolPCG: 1e-5
  maxiterPCG: 500
  nrun: 30
  num_markers_for_vr: 30
  use_sparse_grm_to_fit: true
  use_pcg_with_sparse_grm: false
  relatedness_cutoff: 0.125
  overwrite_vr: true
